# Rust edition 2021
use_small_heuristics = "Max"
reorder_imports = true
edition = "2021"
version = "Two"

# Use Unix style newlines, with 2 spaces tabulation.
newline_style = "Unix"
tab_spaces = 2
hard_tabs = false

# Make one line functions in a single line
fn_single_line = true

# Format strings
format_strings = true

# Increase the max line width
max_width = 120
comment_width = 100

# Merge nested imports
merge_imports = true

# Enum and Struct alignement
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20

# Reorder impl items: type > const > macros > methods.
reorder_impl_items = true

# Comments and documentation formating
format_code_in_doc_comments = true
match_block_trailing_comma = true
normalize_doc_attributes = true
error_on_line_overflow = true
normalize_comments = true
report_fixme = "Always"
wrap_comments = true
todo = "Always"